{
 "title": "Memecached App Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "app_memory_usage_percent" }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "clamp_min(max(increase(app_http_requests_total[15m]),0)/900,0)",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Average Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "clamp_min(((rate(app_http_request_duration_seconds_sum[15m])/rate(app_http_request_duration_seconds_count[15m])) or vector(0)) * 1000,0)",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}